#!/bin/bash

ASMFILE=boot.asm

Build="$PWD"/Build/

BuildName=BootOS

iswrng=false

if [ "$1" == "-r" ] || [ "$1" == "--run" ] ; then

    iswrng=false
    if ( ls "$PWD" | grep -i Build ); then 
        mkdir -pv "$Build"
    fi
    nasm -f bin -o "$BuildName".bin "$ASMFILE"

    mv "$BuildName".bin "$Build"

    pushd "$Build" || exit
    qemu-system-i386 -fda "$BuildName".bin
    dd if=/dev/zero of="$BuildName".img bs=1024 count=1440
    dd if="$BuildName".bin of="$BuildName".img seek=0 count=1 conv=notrunc
    qrencode -r "$BuildName".bin -8 -o "$BuildName"FDD.png
    popd || exit

else
    iswrng=true
fi

if [ "$1" == "-b" ] || [ "$1" == "--build" ] ; then

    iswrng=false
    if ( ls "$PWD" | grep -i Build ); then 
        mkdir -pv "$Build"
    fi

    nasm -f bin -o "$BuildName".bin "$ASMFILE"
    nasm -f bin -o "$BuildName".com "$ASMFILE"

    mv "$BuildName".bin "$Build"
    mv "$BuildName".com "$Build"

    pushd "$Build" || exit
    dd if=/dev/zero of="$BuildName".img bs=1024 count=1440
    dd if="$BuildName".bin of="$BuildName".img seek=0 count=1 conv=notrunc
    qrencode -r "$BuildName".bin -8 -o "$BuildName"FDD.png
    popd || exit
else
    iswrng=true
fi
if [ "$1" == "-i" ] || [ "$1" == "--install" ]; then
    iswrng=false
    sudo apt-get install nasm
fi
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    iswrng=true
fi

if [ $iswrng == "true" ]; then
    printf "\nNASM Builder \n  \n-r --run : To run the created image using QEMU \n  \n-b --build : To build the asm file without running it \n  \n-h --help : To display this message \n  \n-i --install : To install nasm from apt package manager\n \n"
fi
