#!/bin/bash

Build="$PWD"/Build/

if ( ls "$PWD" | grep -i Build ); then 
    mkdir -pv "$Build"
fi

nasm -f bin -o boot.bin boot.asm

mv boot.bin "$Build"

pushd $Build || exit
qemu-system-i386 -fda boot.bin
dd if=/dev/zero of=boot.img bs=1024 count=1440
dd if=boot.bin of=boot.img seek=0 count=1 conv=notrunc
qrencode -r boot.bin -8 -o bootFDD.png